# Generated by Django 4.2 on 2023-06-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='call_status',
            field=models.CharField(default='inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_path',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
