# Generated by Django 4.2 on 2023-06-30 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_call_status_alter_media_media_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='call_status',
        ),
        migrations.CreateModel(
            name='VideoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
            ],
        ),
    ]
